### ISSUE TITLE
Login screen improvements

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocollect-universal-ios#1]
The login form asks for your username and password. The username is an email addressfor AUTH, so I think we should put email address in there. We've had quite a few users get caught by this and they get stuck as they don't know what their username is. We've changed the ALA form to reflect this:

![image](https://user-images.githubusercontent.com/532845/28344668-7004a83e-6c68-11e7-8c0a-07f35b2c37ec.png)

The other suggestion is to add `type="email"` to the input for the username/email address. This changes the keyboard layout and puts the `@` symbol on the keyboard so the user doesn't have to switch keyboard screens (see [this blog](http://blog.teamtreehouse.com/using-html5-input-types-to-enhance-the-mobile-browsing-experience) for details).

**Comment by sat01a** [comment]
Thanks @nickdos. 
How did I miss that!
