### ISSUE TITLE
App home screen suggestions

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocollect-universal-ios#2]
When logged in, the user is taken to the "home screen" saying "G'day <user_name>" and showing a moth photo. 

My suggestion is to replace the moth photo with the ALA logo. The main reason is its not clear what app you are in - there is no ALA name or logo (except right at the bottom for the app version, which is too subtle). 

If a users locks their screen and then unlocks the phone later on (hours later) then they'd be confused as to what app they're in. I think we need **strong branding on this page** with both the logo and at least "ALA" or better still "Atlas of Living Australia".

**Comment by sat01a** [comment]
Sounds good.
